# Generated by Django 4.2.7 on 2023-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
