# Generated by Django 4.2.7 on 2023-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
